<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sistemaSolar [
    <!ELEMENT sistemaSolar (cuerpo*)>
    <!ELEMENT cuerpo (planeta|satelite|asteroide)*>
    <!-- aÃ±adimos asterisco para poder poner mas de un elemento-->
    <!ELEMENT planeta (#PCDATA)>
    <!ELEMENT satelite (#PCDATA)>
    <!ELEMENT asteroide (#PCDATA)>
]>
<sistemaSolar>
    <cuerpo>
        <planeta>Tierra</planeta>
        <satelite>Luna</satelite>
        <asteroide>Ceres</asteroide>
    </cuerpo>
    <!-- metemos la etiqueta asteroide dentro de cuerto-->
</sistemaSolar>