<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE coches [
    <!ELEMENT coches (coche+)>
    <!ELEMENT coche (marca, modelo, puertas, color, precio)>
    <!ATTLIST coche matricula CDATA #REQUIRED>
    <!ELEMENT marca (#PCDATA)>
    <!ELEMENT modelo (#PCDATA)>
    <!ELEMENT puertas (#PCDATA)>
    <!ELEMENT color (#PCDATA)>
    <!ELEMENT precio (#PCDATA)>
    <!ATTLIST precio venta CDATA #REQUIRED>
]>

<coches>
    <coche matricula="1234LDK">
        <marca>Peugeot</marca>
        <modelo>2008</modelo>
        <puertas>5</puertas>
        <color>Azul</color>
        <precio venta="nuevo">38000</precio>
    </coche>
    <coche matricula="4321ELS">
        <marca>Ford</marca>
        <modelo>Mustang</modelo>
        <puertas>3</puertas>
        <color>Negro</color>
        <precio venta="ocasion">50000</precio>
    </coche>
</coches>